### ISSUE TITLE
Include LICENSE in the release packages

### ISSUE THREAD

**Issue by foip** [zerodaycode/Zork#50]
## Feature Request

The MIT license is a custom license as it includes a copyright notice.
It should therefore be included in the release packages.

### Solution
This patch should fix the [.github/workflows/release.yml](https://github.com/zerodaycode/Zork/blob/main/.github/workflows/release.yml) to include LICENSE in the linux package.
~~~
70c70
<           tar -czvf zork-linux.tar.gz ./dist/zork++
---
>           tar -czvf zork-linux.tar.gz ./dist/zork++ ./LICENSE
~~~

A Similar change should be made to [release-config/windows-installer-zork.iss](https://github.com/zerodaycode/Zork/blob/main/release-config/windows-installer-zork.iss) in the [Files] section

**Comment by Pyzyryab** [comment]
Hello @foip 

Want you to open a PR with the changes?
