### ISSUE TITLE
Build fails with linker error on linux

### ISSUE THREAD

**Issue by foip** [zerodaycode/Zork#55]
### Description
The build process of the example project fails with the following error on linux
~~~
/usr/bin/ld: cannot open output file : No such file or directory
~~~

### Steps to reproduce
~~~bash
$ source alias.sh
$ CompileZork
~~~

This fails when it tries to compile the project inside the `examples` subdirectory.

### Expected result
The build should finish with the following output:

~~~
[SUCCESS]: Compilation job finished. Total time spent on the process: xxx ms

Hello from an autogenerated Zork project!
RESULT '+': 10
RESULT '-': 6
RESULT '*': 16
RESULT '/': 1
~~~

### Actual result
The build fails with the following output:

~~~
/usr/bin/ld: cannot open output file : No such file or directory
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
~~~

### Possible solution
Following patch for `zork/compiler_tasks.py`
~~~
65c65
<         + '.exe' if constants.OS == constants.WINDOWS else ''
---
>         + ('.exe' if constants.OS == constants.WINDOWS else '')
~~~

The expression basically reads
~~~
("executable" + ".exe") if windows else ("")
~~~
instead of the intended
~~~
"executable" + (".exe" if windows else "")
~~~
if the brackets are omitted.
This leads to the parameter always being empty if the OS is not Windows.

The command line ends up as `clang++ -o "" main.cpp` instead of `clang++ -o calculator main.cpp`.

### Environment
OS: Arch Linux
Python: 3.10.9
Clang: 14.0.6
GNU ld: 2.39.0

**Comment by Pyzyryab** [comment]
Hello @foip and thanks for open this issue.
We tried this now with the lastest changes in main, and we are unable to reproduce the bug. I am using Manjaro, so I am not able to reproduce 100% your environment. 

Can you tell us what version of Zork are you using?
