### ISSUE TITLE
Use a consistent error reporting strategy

### ISSUE THREAD

**Issue by foip** [zerodaycode/Zork#62]
## Refactor

I wanted to start working on the error reporting and wanted to get some input first.
Mostly because it would introduce a new dependency.

Leaking `panics` to the user is a bit ugly in my opinion.
That should only happen if there is an actual bug, not an expected problem like wrong directory permissions.
I believe it is reasonable to think about a consistent error handling strategy early on.

I tried out two crates below.

Any comments or other alternatives to consider?

### color_eyre

The `color_eyre crate` provides a `Report` Error type.
Error handling would look something like that:

~~~Rust
// in utils::template
fn create_directory(path_create: &Path) -> Result<(), color_eyre::Report> {
    DirBuilder::new()
        .recursive(true)
        .create(path_create)
        .wrap_err_with(|| format!("failed to create directory {:?}", path_create))
}


pub fn create_templated_project(...) -> Result<(), color_eyre::Report> {
    // ...
    create_directory(&project_root)?;
    // ...
}

// in main
fn main() -> Result<(), Report> {
    color_eyre::install()?; // install error handler

    let cli_args = CliArgs::parse();
    config_logger(cli_args.verbose, Target::Stdout).expect("Error configuring the logger");

    match cli_args.command {
        Command::Test => todo!("Implement test routine"),
        Command::New {
            name,
            git,
            compiler,
        } => create_templated_project(name, git, compiler.into()),
    }
}
~~~

All functions have return type `Result<(), Report>`. The result of main is then evaluated by the error handler that is installed with `color_eyre::install`.

The error report looks somethin like that.

![color_eyre_report](https://user-images.githubusercontent.com/83360380/211593791-e7e05187-cefa-4e17-a4d9-4472bc1b8d11.png)

### anyhow

Anyhow works similarly.

~~~Rust
fn create_directory(path_create: &Path) -> anyhow::Result<()> {
    DirBuilder::new()
        .recursive(true)
        .create(path_create)
        .with_context(|| format!("failed to create directory {:?}", path_create))
}

fn main() {
    let cli_args = CliArgs::parse();
    config_logger(cli_args.verbose, Target::Stdout).expect("Error configuring the logger");

    let result = match cli_args.command {
        Command::Test => todo!("Implement test routine"),
        Command::New {
            name,
            git,
            compiler,
        } => create_templated_project(name, git, compiler.into()),
    };

    if let Err(e) = result {
        println!("{:#}", e)
    }
}
~~~

Error reporting is not colorful and more simplistic and generally less "stylable".

~~~bash
$ zork new asdf
failed to create directory "./asdf": File exists (os error 17)
~~~

**Comment by Pyzyryab** [comment]
Hello @foip

I see that is a nice approach. Panics are already there for debug purposes now, but I agree that an early approach using `Result` instead of errors will lead to have a more concise and clear API.

There are changes merged from yesterday into the branch on upstream. You can go ahead, create a branch from there and try the alternative `color_eyre crat`. It would be better than panic for sure.

Btw, I don't like too much the `Anyhow` alternative. I would like too see how the API would look with `color_eyre`.

Note that are very preliminar changes from yesterday intending to make an starting point of the project's core, the compiler tasks. Apply changes in the whole codebase where you see that would upgrade our API an we will see how it looks

**Comment by Pyzyryab** [comment]
Well, changes are merged now. I will now merge minimal changes from yesterday that I left on another computer... and you can refactor the whole code up until this point if you like

**Comment by Pyzyryab** [comment]
Changes are applicated now on upstream. Feel free to refactor all the code with `color_eyre`
