### ISSUE TITLE
[docs] Incorrect status badges

### ISSUE THREAD

**Issue by ninjaoflight** [zerodaycode/Zork#83]
## description

> Readme related issues  

some badges like code quality and coverade does not show

- for example the code quality points to pylint but shoud be: [![Code quality and sanity](https://github.com/zerodaycode/Zork/actions/workflows/code-quality.yml/badge.svg)](https://github.com/zerodaycode/Zork/actions/workflows/code-quality.yml)
- and code coverage seems to be: [![Code Coverage](https://github.com/zerodaycode/Zork/actions/workflows/code-coverage.yml/badge.svg)](https://github.com/zerodaycode/Zork/actions/workflows/code-coverage.yml)

**Comment by Pyzyryab** [comment]
Yes, as with #82, they are mistakes but not updating properly the docs after the rewrite process. Thanks for spot them, we will fix them soon!
